version: '3'
services:
  db:
    image: 'mongo:4.4.2'
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - './docker-config/mongodb:/data/configdb'
    ports:
      - '27017:27017'

  authserver:
    container_name: authserver
    build:
      context: ./AuthorizationServer
      dockerfile: Dockerfile
    image: 'authserver:1'
    expose:
      - 9000
    ports:
      - '9000:9000'
    depends_on:
      - db

  resserver:
    container_name: resserver
    build:
      context: ./ResourceServer
      dockerfile: Dockerfile
    image: 'resserver:1'
    expose:
      - 8081
    ports:
      - '8081:8081'
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 'frontend/angular-app:latest'
    volumes:
      # Map ./frontend to ./app for development (remove and rebuild for production)
      # - ./frontend:/app
      # Use a persistent volume for node_modules so that it does not get mapped
      - node_modules:/app/node_modules
    expose:
      - 80
    ports:
      - '8000:80'
    depends_on:
      - resserver

volumes:
  node_modules: