version: '3'
services:
  db:
    image: 'mongo:4.4.2'
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - './docker-config/mongodb:/data/configdb'
    ports:
      - '27017:27017'

  authserver:
    container_name: authserver
    build:
      context: ./AuthorizationServer
      dockerfile: Dockerfile
    image: 'authserver:1'
    expose:
      - 9000
    ports:
      - '9000:9000'
    depends_on:
      - db

  resserver:
    container_name: resserver
    build:
      context: ./ResourceServer
      dockerfile: Dockerfile
    image: 'resserver:2'
    expose:
      - 8081
    ports:
      - '8081:8081'
    depends_on:
      - db

volumes:
  node_modules: